#!/bin/sh
#
# sicherboot file. Installed as dracut to work around missing
# hook support in dracut...

set -e

# Run the real dracut first if it exists
if [ -e /etc/kernel/postinst.d/dracut.SecureBoot ]; then
    /etc/kernel/postinst.d/dracut.SecureBoot "$@"
fi

echo "sicherboot: Installing $1 to ESP"

sicherboot install-kernel "$1"
