#!/bin/sh
#
# sicherboot file. Installed as dracut to work around missing
# hook support in dracut...

set -e

sicherboot_kernel_version="$1"

# Run the real dracut first if it exists
if [ -e /etc/kernel/postinst.d/dracut.SecureBoot ]; then
    . /etc/kernel/postinst.d/dracut.SecureBoot
fi


sicherboot > /dev/null 2>&1 || exit 0

echo "sicherboot: Installing $sicherboot_kernel_version to ESP"

sicherboot install-kernel "$sicherboot_kernel_version"
