#!/bin/sh
#
# jak-systemd-secure-boot file. Installed as dracut to work around missing
# hook support in dracut...

set -e

# Run the real dracut first if it exists
if [ -e /etc/kernel/postinst.d/dracut.SecureBoot ]; then
    /etc/kernel/postinst.d/dracut.SecureBoot
fi

echo "jak-secure-systemd-boot: Installing $1 to ESP"

jak-sb install-kernel "$1"
